In [1]:
import sys
import numpy as np
import pandas as pd
from scipy import stats
from statsmodels.stats.multicomp import pairwise_tukeyhsd

In [21]:
#data_file = sys.argv[1]
data_file ="data.csv"
data = pd.read_csv(data_file)

         qs1       qs2       qs3       qs4       qs5    merge1  partition_sort
0   0.011963  0.012997  0.013968  0.009968  0.010971  0.012932        0.006982
1   0.008975  0.013963  0.012965  0.010970  0.010970  0.010970        0.007983
2   0.011968  0.015957  0.012995  0.011935  0.011003  0.011968        0.007947
3   0.008976  0.015927  0.015958  0.013962  0.012961  0.010970        0.006981
4   0.008977  0.011967  0.014961  0.020947  0.013959  0.016955        0.015962
..       ...       ...       ...       ...       ...       ...             ...
95  0.013995  0.015957  0.015993  0.014924  0.014963  0.015953        0.007982
96  0.014960  0.018955  0.017947  0.017953  0.016985  0.011935        0.008976
97  0.011971  0.018950  0.016956  0.015954  0.014991  0.012965        0.009973
98  0.012933  0.014965  0.020942  0.015954  0.014994  0.012932        0.006985
99  0.010967  0.014992  0.013963  0.010972  0.011934  0.012967        0.006979

[100 rows x 7 columns]

In [8]:
# ANOVA test, to see if any of the groups differ
anova = stats.f_oneway(data.iloc[:,0], data.iloc[:,1], data.iloc[:,2], data.iloc[:,3], data.iloc[:,4], data.iloc[:,5], data.iloc[:,6])
print(anova)
print(anova.pvalue)
#We conclude that yes: with p<0.5 , there is a difference between the means of the groups.

F_onewayResult(statistic=34.50409141249649, pvalue=1.5099431718361843e-36)
1.5099431718361843e-36

In [23]:
# Post Hoc Analysis
data_melt = pd.melt(data)
posthoc = pairwise_tukeyhsd(data_melt['value'], data_melt['variable'], alpha=0.05)
print(posthoc)
fig = posthoc.plot_simultaneous()

        Multiple Comparison of Means - Tukey HSD, FWER=0.05
====================================================================
    group1         group2     meandiff p-adj   lower   upper  reject
--------------------------------------------------------------------
        merge1 partition_sort  -0.0058  0.001 -0.0076  -0.004   True
        merge1            qs1  -0.0022 0.0073  -0.004 -0.0004   True
        merge1            qs2   0.0015 0.1855 -0.0003  0.0033  False
        merge1            qs3   0.0014 0.2414 -0.0004  0.0032  False
        merge1            qs4  -0.0009 0.7393 -0.0027  0.0009  False
        merge1            qs5  -0.0003    0.9 -0.0021  0.0015  False
partition_sort            qs1   0.0037  0.001  0.0019  0.0055   True
partition_sort            qs2   0.0073  0.001  0.0055  0.0091   True
partition_sort            qs3   0.0072  0.001  0.0054   0.009   True
partition_sort            qs4    0.005  0.001  0.0032  0.0067   True
partition_sort            qs5   0.0055  0.001  0.0037  0.0073   True
           qs1            qs2   0.0036  0.001  0.0018  0.0054   True
           qs1            qs3   0.0036  0.001  0.0018  0.0054   True
           qs1            qs4   0.0013 0.3568 -0.0005  0.0031  False
           qs1            qs5   0.0018 0.0392  0.0001  0.0036   True
           qs2            qs3  -0.0001    0.9 -0.0019  0.0017  False
           qs2            qs4  -0.0024  0.002 -0.0042 -0.0006   True
           qs2            qs5  -0.0018 0.0507 -0.0036     0.0  False
           qs3            qs4  -0.0023 0.0033 -0.0041 -0.0005   True
           qs3            qs5  -0.0017 0.0722 -0.0035  0.0001  False
           qs4            qs5   0.0006    0.9 -0.0012  0.0024  False
--------------------------------------------------------------------

In [24]:
print(data.mean())

qs1               0.011841
qs2               0.015477
qs3               0.015400
qs4               0.013112
qs5               0.013686
merge1            0.014000
partition_sort    0.008158
dtype: float64